import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, CheckCircle2, MapPin } from "lucide-react";
import { Button } from "@/components/ui/button";
import { JsonLd } from "@/components/json-ld";
import { areaBySlug, areas, questions, site, topics } from "@/lib/roofing-data";
export function generateStaticParams(){return areas.map(area=>({slug:area.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const area=areaBySlug(slug);if(!area)return{};return{title:`Roofing Questions in ${area.name}`,description:`Plain-English roofing answers and property-specific quotation enquiries for homeowners in ${area.name} and nearby areas.`,alternates:{canonical:`/areas/${slug}`}}}
export default async function AreaPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const area=areaBySlug(slug);if(!area)notFound();const popular=questions.filter((_,i)=>i%7===areas.findIndex(a=>a.slug===slug)%7).slice(0,6);const schema={"@context":"https://schema.org","@type":"Service",name:`Roofing advice and quotations in ${area.name}`,provider:{"@type":"RoofingContractor",name:site.operator,url:site.companyWebsite,telephone:site.phone},areaServed:{"@type":"City",name:area.name},url:`${site.url}/areas/${slug}`};return <main><JsonLd data={schema}/><section className="page-hero"><div className="container-wide"><p className="eyebrow light"><MapPin/> North East roofing guidance</p><h1>Roofing questions in {area.name}, answered.</h1><p>Understand the problem first. If the answer needs applying to your property, request a direct inspection and written quotation from J&L Welch.</p><Button asChild size="lg" className="answer-accent"><Link href="/request-a-quote">Request a quote in {area.name} <ArrowRight/></Link></Button></div></section><section className="section container-wide content-split"><article className="prose-panel"><p className="eyebrow">Local guidance</p><h2>Roof problems around {area.name}</h2><p>Exposure, driving rain, older coverings, chimney junctions, flat-roof additions and loft condensation are common reasons homeowners search for help. The correct answer still depends on the individual construction and evidence.</p><p>J&L Welch considers suitable enquiries in {area.name} and nearby communities including {area.nearby.join(", ")}. Quotations are property-specific and subject to survey availability.</p><h3>Popular questions</h3><ul className="local-question-list">{popular.map(item=><li key={item.slug}><Link href={`/questions/${item.slug}`}>{item.question}<ArrowRight/></Link></li>)}</ul></article><aside className="side-card"><p className="eyebrow">What J&L Welch can assess</p><ul className="check-list">{topics.slice(0,7).map(topic=><li key={topic.slug}><CheckCircle2/>{topic.name}</li>)}</ul><Button asChild><Link href="/request-a-quote">Send your question</Link></Button></aside></section></main>}
