import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BookOpenCheck, CheckCircle2, MapPin, MessageCircleQuestion, ShieldCheck, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { JsonLd } from "@/components/json-ld";
import { QuestionSearch } from "@/components/question-search";
import { areas, questions, site, topics } from "@/lib/roofing-data";

export default function Home(){const schema={"@context":"https://schema.org","@type":"WebSite",name:site.name,url:site.url,publisher:{"@id":`${site.url}/#publisher`}};return <main><JsonLd data={schema}/><section className="answer-hero"><Image src="/jl-welch-roofing-hero.png" alt="Roofing team working on a slate roof in North East England" fill priority sizes="100vw" className="answer-hero-image"/><div className="answer-hero-shade"/><div className="container-wide answer-hero-inner"><div><p className="eyebrow light"><MessageCircleQuestion/> Ask it exactly as you would say it</p><h1>Got a roofing question? Get a straight answer.</h1><p className="hero-intro">Leaks, prices, flat roofs, new roofs, condensation, guarantees and storm damage—search clear answers written for North East homeowners.</p><QuestionSearch/><div className="hero-proof"><span><CheckCircle2/> {questions.length} detailed answers</span><span><BookOpenCheck/> Plain English</span><span><MapPin/> North East focused</span></div></div></div></section><section className="operator-strip"><div className="container-wide"><span>Advice and quotation service operated by</span><strong>J & L Welch Roofing & Paving Services Ltd</strong><span>Trusted roofing contractors serving Durham and the North East</span></div></section>
<section className="section container-wide"><div className="section-heading"><div><p className="eyebrow">Browse by problem</p><h2>Start with the part that is worrying you.</h2></div><p>You do not need to know the technical name. Choose the closest subject and follow the questions people normally ask next.</p></div><div className="topic-grid">{topics.map((topic,index)=><Link href={`/topics/${topic.slug}`} key={topic.slug}><span className="topic-number">{String(index+1).padStart(2,"0")}</span><h3>{topic.name}</h3><p>{topic.description}</p><span className="text-link">View answers <ArrowRight/></span></Link>)}</div></section>
<section className="dark-answer-section"><div className="container-wide answer-split"><div><p className="eyebrow light">The answer comes first</p><h2>Useful guidance before anyone tries to sell you a roof.</h2><p>Every page explains the issue, what evidence matters, what you can safely check and when a property-specific inspection is sensible. No fake instant prices and no pretending every defect needs replacement.</p><ul className="principle-list"><li><CheckCircle2/>Repair where repair is technically sensible</li><li><CheckCircle2/>Replace when the whole system is failing</li><li><CheckCircle2/>Compare written specifications, not headline prices</li><li><CheckCircle2/>Keep safety, ventilation and compliance in the decision</li></ul></div><aside className="expert-card"><Wrench/><p className="eyebrow">Need the answer applied to your property?</p><h3>Ask J&L Welch to inspect and quote.</h3><p>Over 20 years of combined roofing experience. Bespoke new-roof systems individually specified following inspection. Detailed written quotations provided.</p><Button asChild size="lg" className="answer-accent"><Link href="/request-a-quote">Request a quotation <ArrowRight/></Link></Button><small>No obligation. Your enquiry goes directly to J&L Welch Roofing.</small></aside></div></section>
<section className="section area-answer-section"><div className="container-wide"><div className="section-heading"><div><p className="eyebrow">Local context</p><h2>Answers for North East homes and weather.</h2></div><p>Exposure, roof age, local housing types and access all affect the practical answer. Browse guidance for your nearest area.</p></div><div className="area-answer-grid">{areas.map(area=><Link href={`/areas/${area.slug}`} key={area.slug}><MapPin/><span><strong>{area.name}</strong><small>{area.nearby.slice(0,3).join(" · ")}</small></span><ArrowRight/></Link>)}</div></div></section>
<section className="section container-wide leader-section"><div><ShieldCheck/><p className="eyebrow">The quotation provider</p><h2>Why the site refers suitable enquiries to J&L Welch.</h2><p>J&L Welch is a North East roofing contractor with over 20 years of combined experience. The team handles new roofs, flat roofs, worthwhile repairs, commercial roofing and full roofline work. The company—not an anonymous broker—takes responsibility for any quotation it issues.</p></div><div className="leader-facts"><span><strong>North East</strong><small>Regional operating area</small></span><span><strong>Property-specific</strong><small>Inspection and written scope</small></span><span><strong>Direct</strong><small>No third-party lead auction</small></span></div></section>
<section className="final-cta"><div className="container-wide"><div><p className="eyebrow light">Still unsure?</p><h2>Tell us what the roof is doing.</h2><p>Send the postcode, issue, timescale and photographs. J&L Welch will confirm the sensible next step.</p></div><Button asChild size="lg" className="answer-accent"><Link href="/request-a-quote">Ask for a quotation <ArrowRight/></Link></Button></div></section></main>}
