"use client";
import { useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, ImagePlus, Loader2 } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
const jobTypes=["Active roof leak","Roof repair","New pitched roof","Flat roof","Slate or tile work","Chimney, leadwork or valley","Fascia, soffit or guttering","Condensation or insulation","Roof inspection","Other roofing question"];
type Fields={category:string;urgency:string;propertyType:string;postcode:string;town:string;description:string;firstName:string;email:string;phone:string;consent:boolean};
const initial:Fields={category:"",urgency:"",propertyType:"",postcode:"",town:"",description:"",firstName:"",email:"",phone:"",consent:false};
export function QuoteRequestForm(){const [step,setStep]=useState(1);const [fields,setFields]=useState(initial);const [photos,setPhotos]=useState<File[]>([]);const [submitting,setSubmitting]=useState(false);const [result,setResult]=useState<{ok:boolean;message:string}|null>(null);const update=(key:keyof Fields,value:string|boolean)=>setFields(v=>({...v,[key]:value}));const canContinue=step===1?!!fields.category&&!!fields.urgency&&!!fields.propertyType:step===2?fields.postcode.length>=3&&fields.description.length>=20:true;
async function submit(){setSubmitting(true);setResult(null);const form=new FormData();Object.entries(fields).forEach(([key,val])=>form.append(key,String(val)));photos.forEach(file=>form.append("photos",file));try{const response=await fetch("/api/jobs",{method:"POST",body:form});const data=await response.json() as {message?:string;error?:string};if(!response.ok)throw new Error(data.error||"Submission failed");setResult({ok:true,message:data.message||"Enquiry submitted"});setStep(4)}catch(error){setResult({ok:false,message:error instanceof Error?error.message:"Please try again."})}finally{setSubmitting(false)}}
return <div className="job-form-shell"><div className="form-progress"><span>Step {Math.min(step,3)} of 3</span><Progress value={step===4?100:(step/3)*100}/></div>{result&&!result.ok&&<Alert variant="destructive"><AlertTitle>Check the form</AlertTitle><AlertDescription>{result.message}</AlertDescription></Alert>}
{step===1&&<div className="form-step"><p className="kicker">The question or job</p><h2>What would you like J&L Welch to look at?</h2><div className="field-grid"><div><Label>Closest category *</Label><Select value={fields.category} onValueChange={v=>update("category",v)}><SelectTrigger><SelectValue placeholder="Choose one"/></SelectTrigger><SelectContent>{jobTypes.map(type=><SelectItem value={type} key={type}>{type}</SelectItem>)}</SelectContent></Select></div><div><Label>How urgent is it? *</Label><Select value={fields.urgency} onValueChange={v=>update("urgency",v)}><SelectTrigger><SelectValue placeholder="Select urgency"/></SelectTrigger><SelectContent><SelectItem value="Emergency / make safe">Emergency / make safe</SelectItem><SelectItem value="Within 2 weeks">Within 2 weeks</SelectItem><SelectItem value="Within 1–3 months">Within 1–3 months</SelectItem><SelectItem value="Planning ahead">Planning ahead</SelectItem></SelectContent></Select></div><div><Label>Property type *</Label><Select value={fields.propertyType} onValueChange={v=>update("propertyType",v)}><SelectTrigger><SelectValue placeholder="Select property"/></SelectTrigger><SelectContent>{["Terraced house","Semi-detached house","Detached house","Bungalow","Flat / apartment","Commercial property","Other"].map(type=><SelectItem value={type} key={type}>{type}</SelectItem>)}</SelectContent></Select></div></div></div>}
{step===2&&<div className="form-step"><p className="kicker">The property</p><h2>Where is it and what is happening?</h2><div className="field-grid two"><div><Label htmlFor="postcode">Postcode *</Label><Input id="postcode" value={fields.postcode} onChange={e=>update("postcode",e.target.value)} placeholder="e.g. DH1 3AA"/></div><div><Label htmlFor="town">Town</Label><Input id="town" value={fields.town} onChange={e=>update("town",e.target.value)} placeholder="Durham"/></div></div><div className="field-block"><Label htmlFor="description">Describe your question or the work *</Label><Textarea id="description" value={fields.description} onChange={e=>update("description",e.target.value)} rows={6} placeholder="Where is the problem? When does it happen? What covering can you see? Include anything already tried."/><small>{fields.description.length}/20 minimum characters</small></div><div className="upload-box"><Label htmlFor="photos"><ImagePlus/> Add up to five photographs</Label><Input id="photos" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" multiple onChange={e=>setPhotos(Array.from(e.target.files||[]).slice(0,5))}/><small>{photos.length?`${photos.length} photograph${photos.length===1?"":"s"} selected`:"External and internal photographs can make the first assessment more useful."}</small></div></div>}
{step===3&&<div className="form-step"><p className="kicker">Your details</p><h2>Where should J&L Welch contact you?</h2><div className="field-grid two"><div><Label htmlFor="firstName">First name *</Label><Input id="firstName" value={fields.firstName} onChange={e=>update("firstName",e.target.value)}/></div><div><Label htmlFor="phone">Phone *</Label><Input id="phone" inputMode="tel" value={fields.phone} onChange={e=>update("phone",e.target.value)}/></div><div><Label htmlFor="email">Email *</Label><Input id="email" type="email" value={fields.email} onChange={e=>update("email",e.target.value)}/></div></div><div className="consent-row"><Checkbox id="consent" checked={fields.consent} onCheckedChange={v=>update("consent",v===true)}/><Label htmlFor="consent">I agree that North East Roof Answers may pass these details directly to J&L Welch Roofing & Paving Services Ltd so it can assess and respond to my enquiry. *</Label></div><p className="form-note">This is a direct J&L Welch quotation enquiry. Your details are not offered to a contractor marketplace.</p></div>}
{step===4&&<div className="success-state"><CheckCircle2/><p className="kicker">Enquiry received</p><h2>{result?.message}</h2><p>J&L Welch will review the question, location and photographs before confirming the sensible next step.</p><Button onClick={()=>{setFields(initial);setPhotos([]);setResult(null);setStep(1)}} variant="outline">Send another enquiry</Button></div>}
{step<4&&<div className="form-actions">{step>1?<Button variant="outline" onClick={()=>setStep(step-1)}><ArrowLeft/> Back</Button>:<span/>}{step<3?<Button onClick={()=>setStep(step+1)} disabled={!canContinue}>Continue <ArrowRight/></Button>:<Button onClick={submit} disabled={submitting||!fields.firstName||!fields.email||!fields.phone||!fields.consent}>{submitting?<Loader2 className="animate-spin"/>:<CheckCircle2/>} Request quotation</Button>}</div>}</div>}
