import type { AdditionalQuestionSeed } from "./additional-roofing-data";

export const authorityQuestionSeeds: AdditionalQuestionSeed[] = [
  // Leaks, specialist defects and shared roofs
  ["who-is-responsible-for-a-leak-on-a-shared-roof","Who is responsible when a shared roof leaks?","Responsibility depends on ownership, leases, deeds and the location of the defect. The physical source of water and the legal repair obligation are separate questions.","leaks-and-repairs",["Check title and lease documents","Record the defect before agreeing liability","Coordinate one safe repair specification across the roof"]],
  ["why-does-my-dormer-roof-keep-leaking","Why does my dormer keep leaking?","Dormers concentrate junctions between cheeks, windows, flashings and the main roof. Repeated patching often misses movement, drainage or an incomplete weathering detail.","leaks-and-repairs",["Inspect cheeks, sill and head flashings","Check the roof-to-dormer junction","Assess insulation and condensation as well as rain entry"]],
  ["why-is-water-coming-through-my-party-wall","Why is rainwater appearing near the party wall?","Water may enter through shared chimney details, parapet copings, flashings or one side of the roof and then travel along masonry or timber.","leaks-and-repairs",["Inspect both sides where permission allows","Check parapet and chimney junctions","Agree evidence before attributing blame"]],
  ["can-a-leaking-roof-cause-dry-rot","Can a leaking roof cause dry rot?","Persistent moisture can create conditions for timber decay, including fungal attack. The roof leak, ventilation, extent of affected timber and drying strategy all need attention.","leaks-and-repairs",["Stop water entry promptly","Obtain specialist timber assessment where suspected","Do not seal damp timber behind new finishes"]],
  ["why-is-my-roof-creaking-in-the-wind","Why does my roof creak when it is windy?","Some movement noise can be normal, but new or severe sounds may indicate loose coverings, stressed fixings, bracing issues or movement at roof junctions.","leaks-and-repairs",["Note wind direction and location","Inspect external loose components safely","Seek structural advice for visible movement"]],
  ["can-roof-leaks-trigger-electrical-faults","Can a roof leak cause electrical faults?","Yes. Water reaching cables, junctions, lights or consumer equipment can create shock and fire risks even after visible dripping stops.","leaks-and-repairs",["Keep clear of wet fittings","Isolate circuits only if safe","Use a qualified electrician as well as repairing the roof"]],

  // New builds, structures and alterations
  ["should-i-replace-my-roof-before-solar-panels","Should I replace an old roof before installing solar panels?","If the roof is approaching major renewal, reroofing first can avoid paying twice for panel removal and access. The decision should use actual condition and remaining life.","new-roofs",["Survey coverings, fixings and structure","Compare remaining roof life with panel life","Coordinate compatible mounting details"]],
  ["what-is-roof-spread","What is roof spread and how serious is it?","Roof spread is outward movement at the supporting walls, often linked to inadequate restraint or altered structure. Cracking or distortion warrants structural assessment.","new-roofs",["Look for wall displacement and ceiling cracks","Do not remove ties or struts without design","Use a structural engineer where movement is suspected"]],
  ["can-rotten-rafters-be-repaired","Can rotten rafters be repaired without replacing the whole roof structure?","Localised decay may be repaired or strengthened, but the moisture source, remaining section and load path must be established before choosing a detail.","new-roofs",["Expose enough timber to find sound material","Stop the moisture cause","Get structural design for significant repairs"]],
  ["what-is-the-difference-between-rafters-and-trusses","What is the difference between rafters and roof trusses?","Rafters are individual sloping structural members; prefabricated trusses form engineered assemblies whose components work together and should not be altered casually.","new-roofs",["Identify the structural system first","Do not cut truss webs for storage or services","Seek design approval for alterations"]],
  ["can-i-convert-a-pitched-roof-to-a-flat-roof","Can I convert a pitched roof into a flat roof?","Potentially, but it is a structural and planning alteration involving drainage, insulation, waterproofing, wind loading and Building Regulations—not a simple covering change.","new-roofs",["Check planning constraints","Obtain structural and drainage design","Compare whole-life risk before changing form"]],
  ["what-should-a-self-builder-specify-for-a-roof","What should a self-builder specify for a new roof?","The design should coordinate structure, covering, pitch, wind loading, underlay, battens, insulation, airtightness, ventilation, drainage, fire safety and interfaces.","new-roofs",["Resolve details before ordering materials","Use product-specific fixing calculations","Define inspection and handover responsibilities"]],

  // Flat roofs, commercial and green roofs
  ["can-an-asbestos-garage-roof-be-overclad","Can an asbestos-cement garage roof be overclad?","Sometimes, subject to condition, structure, condensation, fixings and asbestos-management requirements. Overcladding does not remove the asbestos liability.","flat-roofs",["Arrange an asbestos assessment","Confirm structural capacity","Record retained asbestos for future owners and contractors"]],
  ["is-an-asbestos-garage-roof-dangerous","Is an asbestos-cement garage roof dangerous?","Intact asbestos cement is generally lower risk than damaged friable material, but drilling, breaking or cleaning can release fibres. Identification and controlled work are essential.","flat-roofs",["Do not pressure-wash or drill it","Use competent asbestos advice","Keep people away from broken debris"]],
  ["can-a-flat-roof-be-made-into-a-roof-terrace","Can an existing flat roof become a roof terrace?","Only after checking structure, waterproofing protection, drainage, guarding, access, fire safety, planning and overlooking. A normal flat roof is not automatically a trafficable deck.","flat-roofs",["Obtain structural calculations","Design independent protection for the membrane","Check planning and Building Regulations"]],
  ["what-is-a-green-roof","What is a green roof and can I add one?","A green roof adds vegetation, growing medium, drainage and protection above waterproofing. The extra saturated load and maintenance must be designed into the structure.","flat-roofs",["Check wet-load structural capacity","Use root-resistant compatible layers","Provide safe access and drainage maintenance"]],
  ["how-often-should-a-commercial-flat-roof-be-inspected","How often should a commercial flat roof be inspected?","Frequency should reflect system, age, exposure, foot traffic and warranty terms, with additional checks after storms or works by other trades.","flat-roofs",["Keep a dated inspection record","Clear outlets and identify damage early","Control access by other contractors"]],
  ["can-a-warehouse-roof-be-repaired-while-open","Can a warehouse roof be repaired while the business stays open?","Often yes, with phased work, exclusion zones, dust and noise controls, weather planning and coordination around staff, stock and processes.","flat-roofs",["Plan internal and external segregation","Protect sensitive stock","Agree emergency and shutdown procedures"]],

  // Commercial terms and buying decisions
  ["what-is-a-planned-roof-maintenance-contract","What is a planned roof-maintenance contract?","It schedules inspection, cleaning, minor repairs and reporting to reduce emergency failures and support warranties. The scope and response obligations must be measurable.","costs-and-quotes",["Define visit frequency and deliverables","Separate included repairs from chargeable work","Track recurring defects and lifecycle cost"]],
  ["how-should-a-managing-agent-procure-roofing-work","How should a managing agent compare roofing tenders?","Use one survey-led specification, consistent access assumptions and clear evaluation criteria. Otherwise different contractors may price entirely different risks.","costs-and-quotes",["Issue the same scope to every bidder","Compare exclusions and provisional sums","Assess programme, competence and resident protection"]],
  ["what-is-a-roofing-schedule-of-rates","What is a schedule of rates for roofing work?","It lists agreed unit prices for defined work and can speed recurring maintenance. It does not replace inspection or authorisation for unlisted defects.","costs-and-quotes",["Define units and access assumptions","Set review dates for rates","Require evidence for quantities claimed"]],
  ["should-i-get-three-roofing-quotes","Do I always need three roofing quotations?","Multiple comparable quotes can test value, but three vague scopes are less useful than one robust diagnosis and specification. Urgency and survey cost also matter.","costs-and-quotes",["Compare like with like","Investigate major outliers","Do not delay urgent safety work for an arbitrary number"]],
  ["how-much-contingency-should-i-allow-for-a-reroof","How much contingency should I allow for a reroof?","The right contingency depends on how much structure is concealed and the quality of the survey. Older complex roofs normally justify more allowance than open, recently inspected construction.","costs-and-quotes",["List credible hidden risks","Use capped allowances where possible","Keep contingency outside the contractor's base price"]],
  ["is-roof-finance-more-expensive-than-paying-cash","Is financing a roof more expensive than paying cash?","Usually, once interest and fees are included. Compare total repayable cost, affordability and consumer protections rather than focusing only on the monthly payment.","costs-and-quotes",["Check the total amount repayable","Stress-test household income","Avoid delaying an emergency solely to chase cheap credit"]],

  // Solar, heritage and specialist materials
  ["can-solar-panels-damage-roof-tiles","Can solar panels damage roof tiles?","Poor access, unsuitable brackets, cracked tiles and badly sealed penetrations can cause damage. A correctly designed mounting system transfers loads without relying on fragile coverings.","tiles-slates-and-materials",["Inspect the roof before installation","Use compatible structural fixings","Photograph concealed brackets and replaced tiles"]],
  ["can-solar-panels-go-on-natural-slate","Can solar panels be fitted to a natural-slate roof?","Yes, but slate is brittle and needs appropriate brackets, careful access and weathering. Repeated lifting or improvised tile hooks can create hidden cracks.","tiles-slates-and-materials",["Use slate-compatible mounting details","Replace damaged slates immediately","Coordinate roofer and solar installer warranties"]],
  ["how-do-you-roof-a-listed-building","How is roofing work handled on a listed building?","Material, detailing and appearance may require listed-building consent and conservation input. Like-for-like repair is not automatically exempt from every control.","tiles-slates-and-materials",["Contact the conservation authority early","Record and salvage historic materials","Use an approved specification before stripping"]],
  ["what-are-westmorland-green-slates","What are Westmorland green slates?","They are distinctive natural slates historically quarried in Cumbria, valued for colour, texture and heritage use. Reclaimed supply, sorting and laying skill affect cost.","tiles-slates-and-materials",["Confirm provenance and condition","Allow for diminishing courses where required","Use compatible fixings and detailing"]],
  ["are-roof-coatings-worth-it","Are spray-on roof coatings worth the money?","A coating may alter appearance or surface behaviour but cannot repair failed fixings, underlay, battens or structure. Claims of extending life need product-specific evidence.","tiles-slates-and-materials",["Diagnose the roof before coating","Check breathability and manufacturer approval","Compare cost with targeted repair or renewal"]],
  ["can-roof-tiles-be-painted","Can roof tiles be painted safely?","Some compatible systems exist, but preparation can damage tiles and paint can hide rather than cure deterioration. Appearance, slip risk and maintenance must be considered.","tiles-slates-and-materials",["Check tile and coating compatibility","Avoid aggressive pressure washing","Do not describe paint as structural repair"]],

  // Roof windows, air quality and thermal design
  ["why-does-my-roof-window-leak","Why is my roof window leaking?","Possible causes include failed flashings, blocked drainage channels, damaged seals, condensation or poor integration with underlay and coverings.","insulation-and-ventilation",["Separate rain entry from condensation","Check the exact flashing kit","Inspect underlay and insulation around the frame"]],
  ["does-adding-a-roof-window-weaken-the-roof","Does installing a roof window weaken the roof?","Cutting rafters changes the load path. Correct trimming can redistribute loads, but the opening must follow structural design and the window specification.","insulation-and-ventilation",["Identify rafters or engineered trusses","Design trimmers before cutting","Maintain insulation and airtightness around the opening"]],
  ["can-i-add-a-sun-tunnel-to-my-roof","Can I install a sun tunnel through my roof?","Usually possible where structure, route, weathering and ceiling position allow. Bends, length and condensation control affect performance.","insulation-and-ventilation",["Avoid cutting structural members without design","Use the matched external flashing","Insulate and seal the tunnel route"]],
  ["why-is-there-condensation-on-my-roof-window","Why does condensation form on my roof window?","Warm humid air meets a cold glass or frame surface. Room ventilation, heating, reveal insulation and air movement all affect the result.","insulation-and-ventilation",["Use effective bathroom or kitchen extraction","Check insulation around the reveal","Keep trickle ventilation operating where designed"]],
  ["does-mvhr-remove-the-need-for-roof-ventilation","Does MVHR remove the need for roof ventilation?","No. MVHR manages indoor air; the roof still needs the moisture strategy required by its construction, underlay and insulation arrangement.","insulation-and-ventilation",["Commission the MVHR correctly","Keep roof void ventilation where specified","Seal service penetrations through the air barrier"]],
  ["can-spray-foam-insulation-rot-roof-timbers","Can spray-foam insulation cause roof-timber decay?","Problems can arise where foam traps moisture, blocks ventilation or conceals leaks and timber condition. Risk varies with product, design and installation.","insulation-and-ventilation",["Obtain installation documents","Check moisture and ventilation","Seek independent advice before removal or purchase"]],

  // Scaffolding, neighbours and roofline interfaces
  ["can-a-neighbour-refuse-roof-scaffolding-access","Can my neighbour refuse access for roofing scaffolding?","Access depends on ownership, agreement and potentially legal rights for necessary preservation work. Do not assume permission or erect scaffold over neighbouring land without resolving it.","chimneys-leadwork-and-roofline",["Ask early and record agreement","Check licences and legal advice if refused","Design alternative access where practical"]],
  ["can-roofers-work-above-a-conservatory","Can roofers work safely above a conservatory?","Yes, with specifically designed scaffold, bridging or protection. Conservatory roofs should not be treated as working platforms or assumed to carry falling materials.","chimneys-leadwork-and-roofline",["Include bridging in the access design","Protect glazing and occupants","Compare quotes using the same safety provision"]],
  ["does-roof-work-need-a-party-wall-notice","Does roofing work require a Party Wall notice?","Ordinary covering replacement may not, but work to shared walls, chimney breasts, structural bearing or boundary construction can engage the legislation. Get project-specific advice.","chimneys-leadwork-and-roofline",["Identify shared structural work","Serve notices before controlled work where required","Do not rely on the roofer for legal determination"]],
  ["who-owns-a-shared-chimney-stack","Who is responsible for a shared chimney stack?","Ownership and repair obligations depend on the title, physical boundary and agreements. Both sides may need coordinated access even where liability is disputed.","chimneys-leadwork-and-roofline",["Check deeds and survey evidence","Agree one repair detail","Record cost-sharing separately from technical urgency"]],
  ["can-birds-nesting-under-tiles-damage-a-roof","Can birds nesting beneath roof tiles cause damage?","Nesting material can block airflow and drainage, while displaced coverings admit weather. Active nests and protected species must be handled lawfully.","chimneys-leadwork-and-roofline",["Do not disturb active nests unlawfully","Repair entry points at the appropriate time","Use ventilation-compatible bird protection"]],
  ["how-do-i-stop-birds-entering-my-eaves","How can I stop birds entering through the eaves?","Repair openings and use suitable eaves combs, guards or mesh without blocking required ventilation. Timing must respect active-nest protections.","chimneys-leadwork-and-roofline",["Identify the species and nesting status","Preserve ventilation paths","Avoid loose netting that can trap wildlife"]],

  // Compliance, fire and contractual protection
  ["what-fire-rules-apply-to-roof-coverings","What fire-safety rules apply to roof coverings?","Requirements depend on building type, height, use, boundaries and roof system. Coverings, insulation and membranes must be assessed as a tested build-up.","guarantees-and-building-control",["Use declared system classifications","Check boundary and compartmentation requirements","Do not substitute insulation without review"]],
  ["what-is-a-hot-works-permit-for-roofing","What is a hot-works permit for roofing?","It controls work involving flames, heat or sparks through authorisation, precautions, fire watch and post-work checks. It is especially important on occupied and commercial buildings.","guarantees-and-building-control",["Consider flame-free alternatives","Remove or protect combustible material","Document fire-watch responsibilities"]],
  ["do-commercial-roofers-need-construction-phase-plans","Does commercial roofing need a construction phase plan?","Construction work must be planned and managed proportionately under UK health-and-safety duties. The documentation should reflect the actual project and parties.","guarantees-and-building-control",["Define client, designer and contractor duties","Plan access, falls and public protection","Keep arrangements proportionate and site-specific"]],
  ["what-is-a-roof-operation-and-maintenance-manual","What is a roofing operation and maintenance manual?","It gathers the installed system, drawings, products, guarantees, inspection requirements and safe-access information needed to manage the roof after completion.","guarantees-and-building-control",["Specify handover contents before starting","Include as-built changes","Give future contractors the access and warranty rules"]],
  ["should-a-roofer-provide-a-risk-assessment","Should a roofing contractor provide risk assessments?","The contractor should assess and control work risks. Commercial clients commonly require written RAMS; domestic clients should still expect competent planning and safe methods.","guarantees-and-building-control",["Check that documents match the site","Cover falls, lifting and public protection","Do not accept generic paperwork as proof of safe practice"]],
  ["what-happens-to-my-guarantee-if-solar-panels-are-added","Can later solar-panel work affect a roof guarantee?","It may if another contractor alters coverings, penetrations or waterproofing. Check the written terms and coordinate approval before installation.","guarantees-and-building-control",["Notify the guarantee provider first","Photograph mounting details","Separate roof and solar responsibilities in writing"]],

  // Emergencies, asbestos and occupied buildings
  ["what-should-i-do-if-asbestos-roof-sheets-break","What should I do if asbestos-cement roof sheets break?","Keep people away, avoid sweeping or breaking debris further and obtain competent asbestos advice for controlled cleanup and repair.","storms-insurance-and-emergencies",["Do not use power tools or pressure washing","Prevent access to debris","Follow lawful packaging and disposal routes"]],
  ["can-snow-damage-a-flat-roof","Can heavy snow damage a flat roof?","Snow can create substantial load, especially with drifting, blocked drainage or an already deflected deck. Warning signs require urgent exclusion and structural advice.","storms-insurance-and-emergencies",["Do not climb up to shovel it without a plan","Keep people away from sagging areas","Check drainage as thaw begins"]],
  ["what-if-a-tree-falls-on-my-roof","What should I do if a tree falls onto my roof?","Keep everyone out of the affected area, contact emergency services where necessary, notify the insurer and use tree and roofing specialists to coordinate safe removal.","storms-insurance-and-emergencies",["Assume structure may be unstable","Do not cut loaded branches yourself","Document damage before temporary protection"]],
  ["can-a-commercial-roof-leak-shut-down-a-business","How should a business respond to a serious roof leak?","Protect people, electrics, stock and operations first, then isolate the area and coordinate emergency weatherproofing with a documented permanent plan.","storms-insurance-and-emergencies",["Activate business-continuity arrangements","Record damaged stock and equipment","Control roof access and internal exclusion zones"]],
  ["who-do-i-call-for-a-dangerous-chimney","Who should I contact about a dangerous chimney stack?","Keep the area below clear and contact emergency services or the local authority where there is immediate public danger, alongside a competent roofing or masonry contractor.","storms-insurance-and-emergencies",["Do not stand beneath loose masonry","Restrict pavements or entrances safely","Use engineered temporary support where needed"]],
  ["can-lightning-damage-a-roof","Can lightning damage a roof without starting a fire?","Yes. Lightning may damage masonry, metalwork, electrical systems or coverings even without obvious fire. Safety and electrical inspection come before routine repair.","storms-insurance-and-emergencies",["Do not approach damaged conductive components","Check electrics and fire risk","Document the event for insurers"]],

  // Owners, landlords and asset management
  ["who-is-responsible-for-a-roof-in-a-rented-house","Who is responsible for roof repairs in a rented house?","The landlord is generally responsible for the structure and exterior, while tenants must report defects and avoid causing damage. The tenancy and circumstances still matter.","maintenance-and-home-buying",["Report leaks promptly in writing","Keep photographs and access records","Do not delay urgent electrical or ceiling hazards"]],
  ["what-should-a-landlord-roof-inspection-cover","What should a landlord's roof inspection include?","It should record coverings, junctions, drainage, roofline, chimneys, internal moisture, safety risks and repair priorities, with evidence suitable for an asset record.","maintenance-and-home-buying",["Use dated photographs","Separate urgent work from planned renewal","Record tenant-reported symptoms"]],
  ["should-a-block-manager-have-a-roof-maintenance-plan","Should a block manager have a planned roof-maintenance programme?","Yes where roof failure could affect multiple homes or communal areas. Planned inspection and drainage maintenance improve budgeting and reduce emergency disruption.","maintenance-and-home-buying",["Maintain a roof asset register","Coordinate resident access and notices","Track guarantees and previous repairs"]],
  ["can-spray-foam-stop-me-getting-a-mortgage","Can spray-foam roof insulation affect a mortgage?","Some lenders and valuers may require further evidence, inspection or removal because timber and ventilation can be concealed. Requirements vary and must be checked early.","maintenance-and-home-buying",["Ask the intended lender before exchange","Obtain product and installation documents","Do not accept a guaranteed lending outcome"]],
  ["what-is-a-roof-condition-survey-for-a-commercial-building","What is included in a commercial roof-condition survey?","It normally records roof areas, systems, defects, drainage, penetrations, access, priorities and budget recommendations. Testing or opening-up should be separately defined.","maintenance-and-home-buying",["Agree the survey limits","Use annotated photographs and plans","Turn findings into a costed maintenance programme"]],
  ["how-do-i-plan-for-roof-replacement-in-a-service-charge","How should roof replacement be planned through a service charge?","Lease terms, consultation duties, reserve funds, specifications and procurement must be coordinated well before failure. Legal and managing-agent advice may be required.","maintenance-and-home-buying",["Check lease responsibility and consultation rules","Build evidence-based budgets","Communicate scope and programme to leaseholders"]],
];
