export const site = {
  name: "North East Roof Answers",
  url: "https://north-east-roof-answers.johnwelch1234.chatgpt.site",
  email: "jlwelchroofingservices@outlook.com",
  phone: "+447712510024",
  phoneDisplay: "07712 510024",
  operator: "J & L Welch Roofing & Paving Services Ltd",
  companyNumber: "13215186",
  address: "Low Crows House, Wheatley Hill, Durham, DH6 3QL",
  companyWebsite: "https://www.jlwelchroofing.co.uk",
};

export const areas = [
  {slug:"durham",name:"Durham",nearby:["Newton Hall","Bowburn","Coxhoe","Pity Me"]},
  {slug:"newcastle",name:"Newcastle",nearby:["Jesmond","Gosforth","Heaton","Walker"]},
  {slug:"sunderland",name:"Sunderland",nearby:["Penshaw","Ryhope","Seaburn","Houghton-le-Spring"]},
  {slug:"gateshead",name:"Gateshead",nearby:["Low Fell","Whickham","Felling","Blaydon"]},
  {slug:"chester-le-street",name:"Chester-le-Street",nearby:["Sacriston","Pelton","Great Lumley","Birtley"]},
  {slug:"consett",name:"Consett",nearby:["Leadgate","Blackhill","Shotley Bridge","Dipton"]},
  {slug:"stanley",name:"Stanley",nearby:["Tanfield Lea","Annfield Plain","Burnopfield","Beamish"]},
  {slug:"washington",name:"Washington",nearby:["Fatfield","Usworth","Biddick","Oxclose"]},
  {slug:"seaham",name:"Seaham",nearby:["Murton","Dalton-le-Dale","Hawthorn","Easington"]},
  {slug:"peterlee",name:"Peterlee",nearby:["Horden","Shotton Colliery","Blackhall","Easington"]},
  {slug:"bishop-auckland",name:"Bishop Auckland",nearby:["West Auckland","Shildon","Crook","Spennymoor"]},
  {slug:"newton-aycliffe",name:"Newton Aycliffe",nearby:["Aycliffe Village","Heighington","Shildon","Darlington"]},
];

export const topics = [
  {slug:"leaks-and-repairs",name:"Leaks & repairs",description:"Diagnosing leaks, emergency steps, repair choices and when patching stops making sense."},
  {slug:"new-roofs",name:"New roofs",description:"Replacement timing, specifications, surveys, programmes and what a complete quotation should include."},
  {slug:"flat-roofs",name:"Flat roofs",description:"Resitrix SKW, felt, warm-roof construction, falls, outlets, ponding and rooflights."},
  {slug:"costs-and-quotes",name:"Costs & quotations",description:"What drives price, how to compare quotations, deposits, variations and avoiding false economies."},
  {slug:"tiles-slates-and-materials",name:"Tiles, slates & materials",description:"Clay, concrete, natural slate, man-made slate, underlays, battens and compatibility."},
  {slug:"insulation-and-ventilation",name:"Insulation & ventilation",description:"Condensation, warm and cold roofs, U-values, ventilation paths and Building Regulations."},
  {slug:"chimneys-leadwork-and-roofline",name:"Chimneys, leadwork & roofline",description:"Flashings, valleys, pointing, gutters, fascias, soffits, dry ridge and dry verge."},
  {slug:"guarantees-and-building-control",name:"Guarantees & compliance",description:"Workmanship cover, manufacturer warranties, Building Control, CompetentRoofer and handover documents."},
  {slug:"storms-insurance-and-emergencies",name:"Storms, insurance & emergencies",description:"Making safe, documenting damage, insurance claims and deciding what needs urgent attention."},
  {slug:"maintenance-and-home-buying",name:"Maintenance & buying a home",description:"Roof surveys, warning signs, maintenance schedules and questions to ask before purchase."},
];

type QuestionSeed=[string,string,string,string,string[]];
const seeds:QuestionSeed[]=[
  ["why-is-my-roof-leaking-only-when-it-rains-sideways","Why does my roof only leak when rain is blowing sideways?","Wind-driven rain can enter defects that remain dry in vertical rainfall, including laps, flashings, abutments, vents and cracked coverings.","leaks-and-repairs",["Note the wind direction and exact internal staining","Check junctions and penetrations, not only the area directly above","Photographs during the event can materially improve diagnosis"]],
  ["can-a-roof-leak-without-missing-tiles","Can a roof leak without any missing tiles?","Yes. Water can enter through cracked tiles, failed underlay, leadwork, valleys, ridge details, fixings, condensation or defects around penetrations.","leaks-and-repairs",["A complete-looking roof can still leak","Internal staining is not always directly below the defect","A close inspection should assess the full water path"]],
  ["how-do-i-find-where-a-roof-leak-is-coming-from","How do I find where a roof leak is coming from?","Start with the internal entry point, trace moisture upslope where safe and compare it with external junctions, but avoid walking on the roof yourself.","leaks-and-repairs",["Record when the leak occurs","Inspect loft timbers and underlay safely","Use external photographs or a professional survey"]],
  ["is-a-small-roof-leak-an-emergency","Is a small roof leak an emergency?","Treat any active leak seriously. It becomes urgent where water is near electrics, ceilings are bulging, masonry is unstable or damage is rapidly worsening.","leaks-and-repairs",["Isolate affected electrics if safe","Use containers and protect contents","Do not puncture or enter a dangerous ceiling area"]],
  ["can-you-repair-a-roof-in-the-rain","Can a roofer repair a roof while it is raining?","Emergency temporary measures may be possible, but many permanent systems need a dry, safe substrate and suitable weather conditions.","leaks-and-repairs",["Safety and manufacturer conditions come first","Temporary work should be identified as temporary","Agree the permanent follow-up in writing"]],
  ["how-many-times-can-a-roof-be-patched","How many times can a roof be patched before it needs replacing?","There is no fixed number. Replacement becomes more rational when failures are widespread, coverings are brittle, the underlay has failed or repairs no longer address the underlying system.","leaks-and-repairs",["Compare cumulative repair cost with remaining roof life","Check whether defects share one underlying cause","Ask for repair and replacement options where both are viable"]],

  ["how-do-i-know-if-i-need-a-new-roof","How do I know if I need a completely new roof?","Repeated leaks, widespread tile failure, deteriorated underlay, extensive timber defects and an uneconomic repair history can justify replacement, but age alone is not enough.","new-roofs",["Request evidence for each claimed defect","Separate local repairs from system-wide failure","Get the complete proposed specification in writing"]],
  ["how-long-does-a-new-roof-take","How long does a new roof normally take?","Programme depends on size, complexity, access, scaffold, weather, structural repairs and covering. A straightforward house may take days; complex roofs can take considerably longer.","new-roofs",["Ask for the expected working sequence","Allow for weather and hidden timber repairs","Confirm how the property will remain weatherproof"]],
  ["can-i-stay-in-my-house-during-a-new-roof","Can I stay in my house while the roof is replaced?","Usually yes, but expect noise, vibration, scaffold, restricted access and short periods when loft use is unsafe. Special arrangements may be needed for vulnerable occupants.","new-roofs",["Discuss working hours and access","Protect loft contents from dust","Tell the contractor about alarms, pets and vulnerable residents"]],
  ["what-should-a-new-roof-quotation-include","What should a proper new-roof quotation include?","It should define coverings, underlay, battens, ventilation, insulation, ridges, verges, leadwork, timber allowances, scaffold, waste, Building Control, programme, payment and guarantees.","new-roofs",["Reject vague one-line scopes","Check exclusions and provisional allowances","Make sure product names and colours are stated"]],
  ["do-i-need-building-regulations-for-a-new-roof","Do I need Building Regulations approval for a new roof?","Often yes, particularly where more than a defined proportion is renovated or thermal elements are changed. The route should be confirmed for the specific project.","new-roofs",["Agree who notifies Building Control","Confirm insulation and ventilation compliance","Keep the completion documentation"]],
  ["should-old-roof-timbers-be-replaced","Should all old roof timbers be replaced during a reroof?","No. Sound structural timber can normally remain. Decayed, undersized or damaged sections should be identified and treated through a clear allowance or agreed variation.","new-roofs",["Do not pay to replace sound timber without reason","Ask how hidden defects will be priced","Structural concerns may need an engineer"]],

  ["which-flat-roof-system-is-best","What is the best flat-roof system for a house?","There is no universal winner. The right choice depends on deck, falls, insulation, details, foot traffic, fire requirements, budget and installer competence.","flat-roofs",["Compare the full build-up, not only the top layer","Check manufacturer detailing at outlets and edges","Ask who provides workmanship and material cover"]],
  ["what-is-resitrix-skw-flat-roofing","What is Resitrix SKW roofing?","Resitrix SKW is a reinforced EPDM waterproofing membrane with a self-adhesive underside, used for detailed flat-roof applications when installed as a compatible specified system.","flat-roofs",["Deck preparation and primer matter","Details should follow manufacturer guidance","The membrane is only one part of the full roof build-up"]],
  ["is-felt-roofing-still-good","Is modern felt roofing still a good option?","Properly specified multi-layer bituminous felt remains a credible flat-roof system. Performance depends heavily on deck condition, falls, detailing and workmanship.","flat-roofs",["Distinguish modern systems from old shed felt","Check layer specification and capsheet","Confirm warranty and maintenance terms"]],
  ["is-standing-water-on-a-flat-roof-normal","Is standing water on a flat roof normal?","Small temporary areas can occur, but persistent ponding may increase dirt, biological growth and stress. The cause may be inadequate falls, deck movement or restricted outlets.","flat-roofs",["Record how long water remains after rain","Keep outlets clear","Do not assume membrane failure solely from ponding"]],
  ["warm-roof-or-cold-roof-which-is-better","Is a warm flat roof better than a cold flat roof?","Warm-roof construction is often preferred because insulation sits above the deck, helping control condensation and thermal bridging, but the design must suit the building.","flat-roofs",["Do not trap moisture between impermeable layers","Maintain continuity at kerbs and edges","Calculate the build-up rather than copying a generic detail"]],
  ["can-a-flat-roof-be-installed-over-an-old-roof","Can a new flat roof be installed over the old one?","Sometimes an overlay is technically possible, but only after checking moisture, adhesion, deck strength, falls, levels and compatibility. Concealing a wet failed build-up is a false economy.","flat-roofs",["Consider a moisture survey or opening-up","Check door, outlet and edge heights","Make the retained layers explicit in the quotation"]],

  ["how-much-does-a-new-roof-cost-in-the-north-east","How much does a new roof cost in the North East?","Cost depends on measured area, pitch, access, scaffold, covering, insulation, ventilation, leadwork, timber repairs and complexity. A property-specific survey is more reliable than a headline rate.","costs-and-quotes",["Compare like-for-like scopes","Separate VAT and provisional sums","Do not choose from price alone"]],
  ["why-are-roofing-quotes-so-different","Why are two roofing quotations thousands of pounds apart?","They may include different scaffold, materials, insulation, ventilation, timber allowances, waste, compliance and guarantees—or one may simply have missed essential work.","costs-and-quotes",["Create a line-by-line comparison","Ask each contractor to clarify omissions","Treat an unexplained low quote as risk, not automatic value"]],
  ["should-i-pay-a-roofer-a-deposit","Should I pay a roofer a deposit?","Payment structures vary. The key is proportionality, traceability and a written contract. Large unsecured upfront payments increase homeowner risk.","costs-and-quotes",["Link payments to clear milestones","Use the contracting business’s account","Keep invoices and receipts"]],
  ["what-is-a-provisional-sum-in-a-roofing-quote","What does ‘provisional sum’ mean in a roofing quotation?","It is an allowance for work or quantity that cannot yet be confirmed, such as hidden timber repairs. The method for approval and pricing should be stated.","costs-and-quotes",["Ask what evidence triggers the allowance","Agree rates where practical","Require approval before exceeding it"]],
  ["is-the-cheapest-roofing-quote-ever-the-best","Is the cheapest roofing quotation ever the best choice?","It can be, but only where scope, products, competence, insurance and protection are genuinely comparable. Cheap through omission usually becomes expensive later.","costs-and-quotes",["Compare specification before price","Check who carries the contractual responsibility","Avoid verbal extras after work begins"]],
  ["how-do-roofing-variations-work","How should extra roofing work be agreed?","A variation should describe the newly discovered issue, proposed solution, price and programme impact before work proceeds, except for genuine immediate safety action.","costs-and-quotes",["Request photographs of hidden defects","Approve in writing","Keep the revised running total clear"]],

  ["natural-slate-or-man-made-slate","Is natural slate better than man-made slate?","Natural slate can offer distinctive appearance and long service, while fibre-cement or other man-made products can provide consistency and lower weight. Suitability depends on pitch, exposure, structure and budget.","tiles-slates-and-materials",["Specify exact product and origin","Check fixing and lap requirements","Consider planning or conservation constraints"]],
  ["clay-tiles-or-concrete-tiles","Are clay roof tiles better than concrete tiles?","Clay and concrete both have valid uses. Clay is often chosen for appearance and colour stability; concrete can be cost-effective but is generally heavier.","tiles-slates-and-materials",["Confirm structural loading","Use a tile suitable for the pitch and exposure","Compare whole-life appearance as well as price"]],
  ["can-new-tiles-go-on-old-battens","Can new roof tiles be fitted onto the old battens?","Only if battens are demonstrably sound, correctly sized, properly graded and spaced for the new covering. On a full reroof, renewal is commonly the more defensible approach.","tiles-slates-and-materials",["Check grading and condition","Spacing must suit the chosen covering","Do not hide failed underlay beneath retained battens"]],
  ["what-does-roof-underlay-do","What does roofing underlay actually do?","Underlay provides a secondary barrier beneath tiles or slates, helps manage wind-driven rain and interacts with ventilation. It is not intended to replace the primary covering.","tiles-slates-and-materials",["Choose a compatible underlay","Detail laps, penetrations and eaves correctly","Do not assume ‘breathable’ removes every ventilation need"]],
  ["why-do-roof-tiles-crack","Why do roof tiles crack?","Impact, frost, foot traffic, fixing stress, movement, age and manufacturing defects can all contribute. The pattern of damage matters more than one isolated crack.","tiles-slates-and-materials",["Avoid walking on coverings","Check whether damage is local or widespread","Match replacements by product and profile"]],
  ["can-i-change-from-tiles-to-slate","Can I change my roof from tiles to slate?","Potentially, but weight, pitch, batten gauge, headlap, detailing, planning appearance and structural capacity must all be checked before specifying the change.","tiles-slates-and-materials",["Do not assume lighter always means structurally simple","Check planning restrictions","Redesign details around the chosen product"]],

  ["why-is-there-condensation-in-my-loft","Why is my loft wet with condensation?","Warm moist air may be reaching a cold roof space faster than it can disperse. Bathroom extraction, loft hatches, insulation gaps, blocked ventilation and occupancy all matter.","insulation-and-ventilation",["Distinguish condensation from rain entry","Check extract fans discharge outside","Keep ventilation paths clear of insulation"]],
  ["does-a-breathable-membrane-need-ventilation","Does a breathable roofing membrane still need ventilation?","Sometimes. Requirements depend on membrane type, roof build-up, insulation position, moisture load and manufacturer guidance. ‘Breathable’ is not a universal exemption.","insulation-and-ventilation",["Follow the complete system design","Check high- and low-level airflow where required","Avoid mixing incompatible assumptions"]],
  ["how-much-roof-insulation-do-i-need","How much roof insulation do I need?","The answer depends on material conductivity, construction and the target U-value under current requirements. Thickness alone is not a specification.","insulation-and-ventilation",["Calculate rather than guess","Address thermal bridging","Maintain required ventilation gaps"]],
  ["can-too-much-loft-insulation-cause-damp","Can too much loft insulation cause damp?","Insulation itself is not normally the problem, but blocking eaves ventilation, compressing material or leaving air leakage paths can increase condensation risk.","insulation-and-ventilation",["Keep eaves ventilation open","Insulate consistently without compression","Seal obvious warm-air leakage routes safely"]],
  ["what-is-tlx-gold-roof-insulation","What is TLX Gold roofing insulation?","TLX Gold is a multi-foil insulation product used in specified roof build-ups. Its performance depends on installation, air spaces and the rest of the thermal design.","insulation-and-ventilation",["Use the declared system values","Detail joints and air layers correctly","Confirm Building Regulations compliance for the full build-up"]],
  ["why-is-my-bedroom-ceiling-cold-after-a-new-roof","Why is my ceiling still cold after a new roof?","Possible causes include incomplete insulation, thermal bridging, air leakage, an unsuitable build-up or expectations beyond the contracted scope. The specification and installation both need checking.","insulation-and-ventilation",["Review the agreed insulation scope","Use thermal imaging cautiously as evidence","Check junctions at eaves, walls and loft hatches"]],

  ["why-does-lead-flashing-crack","Why does lead flashing crack or split?","Lead expands and contracts. Oversized pieces, poor support, incorrect detailing, fatigue or unsuitable fixings can concentrate movement and cause failure.","chimneys-leadwork-and-roofline",["Use appropriate lead codes and bay lengths","Fix without preventing natural movement","Check the masonry chase and surrounding coverings"]],
  ["does-my-chimney-need-repointing-or-rebuilding","Does my chimney need repointing or rebuilding?","Local open joints may justify repointing; unstable masonry, severe spalling, failed flaunching or structural movement may require more extensive work.","chimneys-leadwork-and-roofline",["Inspect from a safe close position","Separate cosmetic weathering from instability","Check flashings and flaunching at the same time"]],
  ["what-is-dry-ridge","What is a dry-ridge system?","Dry ridge mechanically fixes ridge tiles using a ventilated or sealed proprietary system rather than relying solely on mortar.","chimneys-leadwork-and-roofline",["Compatibility with ridge and roof covering matters","Follow fixing centres and manufacturer instructions","Mortared remnants should not obstruct the system"]],
  ["what-is-dry-verge","What is dry verge and is it worth fitting?","Dry verge uses proprietary units to protect and mechanically finish tile edges at a gable. It can reduce recurring mortar maintenance when correctly matched and fixed.","chimneys-leadwork-and-roofline",["Choose the correct handed or universal system","Fix into sound battens or specified substrate","Poorly fitted units can rattle or detach"]],
  ["why-do-my-gutters-overflow-in-heavy-rain","Why do my gutters overflow only in heavy rain?","Blockages, inadequate falls, leaking joints, undersized outlets, poor alignment or roof areas exceeding capacity can all cause overflow.","chimneys-leadwork-and-roofline",["Clean and water-test first","Check outlet and downpipe restrictions","Consider capacity before simply replacing a joint"]],
  ["should-fascias-be-capped-or-replaced","Should old timber fascias be capped or fully replaced?","Capping can be appropriate over sound, prepared timber. Rotten or structurally poor boards should not be concealed behind new uPVC.","chimneys-leadwork-and-roofline",["Probe and record timber condition","Maintain ventilation at the eaves","State retained timber clearly in the scope"]],

  ["what-does-a-roof-workmanship-guarantee-cover","What should a roofing workmanship guarantee cover?","It should identify the contractor, property, installed work, duration, start point, exclusions, maintenance duties, notification process and remedy.","guarantees-and-building-control",["Read conditions before appointing","Material and workmanship cover are different","Keep proof of payment and handover documents"]],
  ["is-a-20-year-roof-guarantee-automatically-better","Is a 20-year roofing guarantee automatically better?","No. Duration is only useful if the issuing company, scope, exclusions and claims process are credible. A shorter clear guarantee can be worth more than vague headline cover.","guarantees-and-building-control",["Check who stands behind the promise","Read transfer and maintenance terms","Do not confuse manufacturer and installer cover"]],
  ["what-is-an-insurance-backed-guarantee","What is an insurance-backed roofing guarantee?","It is separate cover intended to protect qualifying workmanship obligations in defined circumstances if the original contractor cannot honour them. Terms and eligibility vary.","guarantees-and-building-control",["Confirm eligibility before work","Obtain the actual policy or certificate","Read exclusions and claim conditions"]],
  ["what-is-competentroofer","What is CompetentRoofer and why does it matter?","CompetentRoofer is a UK competent-person route that can allow registered contractors to self-certify qualifying roof-refurbishment work for Building Regulations purposes.","guarantees-and-building-control",["Confirm the work is within scope","Keep the compliance certificate","Registration does not replace a clear contract"]],
  ["what-documents-should-i-get-after-a-new-roof","What documents should I receive when a new roof is finished?","Depending on the job: final invoice, guarantee, Building Regulations certificate, product information, photographs, waste records and any manufacturer or insurance-backed documentation.","guarantees-and-building-control",["Agree the handover list before work","Check names and property address","Store documents for sale and future claims"]],
  ["does-a-roof-guarantee-transfer-to-a-new-owner","Does a roofing guarantee transfer when the house is sold?","Only if the written terms allow transfer and any notification, inspection or fee requirements are followed. Never assume it transfers automatically.","guarantees-and-building-control",["Read the exact transfer clause","Notify the issuer within the required time","Pass maintenance and invoice records to the buyer"]],

  ["what-should-i-do-after-storm-damage-to-my-roof","What should I do immediately after storm damage?","Keep people away from falling debris, protect the interior where safe, photograph damage from ground level, notify the insurer and arrange safe temporary protection.","storms-insurance-and-emergencies",["Do not climb onto a storm-damaged roof","Keep receipts and photographs","Separate emergency mitigation from permanent repair"]],
  ["will-home-insurance-pay-for-a-new-roof","Will home insurance pay for a new roof?","Insurance may cover sudden insured damage but commonly excludes wear, poor maintenance and gradual deterioration. The policy and cause of damage control the answer.","storms-insurance-and-emergencies",["Report the event promptly","Do not describe old deterioration as storm damage","Request the insurer’s decision in writing"]],
  ["can-a-roofer-do-emergency-work-before-insurer-approval","Can a roofer make the roof safe before the insurer approves the claim?","Reasonable emergency mitigation is often necessary, but keep evidence, limit work to what is needed and follow the policy’s notification requirements.","storms-insurance-and-emergencies",["Photograph before and after","Keep temporary-work invoices","Avoid irreversible replacement without authorisation unless safety demands it"]],
  ["is-a-loose-tile-dangerous","Is one loose roof tile dangerous?","Yes. A tile can fall, injure someone or expose the roof to further water and wind damage. Keep the area below clear and arrange safe inspection.","storms-insurance-and-emergencies",["Do not stand beneath loose coverings","Restrict access below","Treat height and wind as safety hazards"]],
  ["what-if-my-ceiling-is-bulging-with-water","What should I do if a ceiling is bulging with water?","Keep everyone out of the area, isolate nearby electrics if safe and seek urgent help. A saturated ceiling can collapse without warning.","storms-insurance-and-emergencies",["Do not stand beneath it","Do not casually puncture it","Call emergency services if there is immediate danger"]],
  ["how-do-i-prove-storm-damage-to-an-insurer","How can I document roof storm damage for an insurer?","Record dates, weather, photographs, internal damage, emergency measures and a professional assessment distinguishing sudden damage from pre-existing wear.","storms-insurance-and-emergencies",["Keep original photo files","Retain damaged items where reasonable","Ask for a factual cause report, not an exaggerated claim"]],

  ["how-often-should-a-roof-be-inspected","How often should I have my roof inspected?","A sensible frequency depends on age, exposure, trees, previous defects and roof type. Inspection after severe weather and before small issues become internal damage is valuable.","maintenance-and-home-buying",["Use ground-level and loft checks between professional visits","Clear outlets and gutters","Record changes over time"]],
  ["what-roof-problems-should-i-look-for-when-buying-a-house","What roof problems should I look for when buying a house?","Look for uneven lines, slipped coverings, staining, daylight in the loft, damp timbers, condensation, failed flashings, old flat roofs and missing compliance documents.","maintenance-and-home-buying",["A general survey may recommend a specialist inspection","Budget for scaffold-dependent work","Ask for invoices, guarantees and certificates"]],
  ["how-old-is-too-old-for-a-roof","How old is too old for a roof?","There is no automatic expiry date. Exposure, product, pitch, installation and maintenance can matter more than age. Condition and remaining serviceability should drive the decision.","maintenance-and-home-buying",["Do not replace solely because of an average lifespan","Check localised versus widespread defects","Plan capital work before repeated failures"]],
  ["should-i-clean-moss-off-my-roof","Should moss be removed from roof tiles?","Heavy moss can hold debris and obstruct drainage, but aggressive scraping or pressure washing can damage coverings. The method must suit the roof material and condition.","maintenance-and-home-buying",["Avoid pressure washing unless specifically appropriate","Protect gutters and people below","Treat the cause of persistent shade and debris where possible"]],
  ["can-i-pressure-wash-my-roof","Can I pressure-wash roof tiles?","It is often risky. High pressure can damage surfaces, force water beneath coverings and invalidate some product guidance. A roof-specific assessment is safer.","maintenance-and-home-buying",["Do not use appearance alone to justify risk","Check manufacturer guidance","Use safe access and controlled methods"]],
  ["what-roof-documents-should-a-house-seller-provide","What roofing documents should a house seller provide?","Ideally invoices, quotations, guarantees, Building Regulations certificates, planning or conservation approvals, insurance-backed documents and maintenance records.","maintenance-and-home-buying",["Match documents to the property and work","Check whether guarantees transfer","Investigate recent work without compliance evidence"]],
];

export type RoofingQuestion={slug:string;question:string;summary:string;topicSlug:string;points:string[]};
export const questions:RoofingQuestion[]=seeds.map(([slug,question,summary,topicSlug,points])=>({slug,question,summary,topicSlug,points}));
export const topicBySlug=(slug:string)=>topics.find(topic=>topic.slug===slug);
export const questionBySlug=(slug:string)=>questions.find(question=>question.slug===slug);
export const areaBySlug=(slug:string)=>areas.find(area=>area.slug===slug);
export const questionsForTopic=(slug:string)=>questions.filter(question=>question.topicSlug===slug);
