import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { questionBySlug, questionsForTopic, topicBySlug, topics } from "@/lib/roofing-data";
export function generateStaticParams(){return topics.map(topic=>({slug:topic.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const topic=topicBySlug(slug);if(!topic)return{};return{title:`${topic.name} Questions & Answers`,description:topic.description,alternates:{canonical:`/topics/${slug}`}}}
export default async function TopicPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const topic=topicBySlug(slug);if(!topic)notFound();const items=questionsForTopic(slug);return <main><section className="page-hero"><div className="container-wide"><p className="eyebrow light">Roofing topic</p><h1>{topic.name}</h1><p>{topic.description}</p></div></section><section className="section container-wide topic-answer-list"><div><p className="eyebrow">Start with your question</p><h2>{items.length} clear answers</h2><p>Open the closest match. Each answer explains practical checks, warning signs and when a quotation is sensible.</p></div><div>{items.map((item,index)=><Link href={`/questions/${item.slug}`} key={item.slug}><span>{String(index+1).padStart(2,"0")}</span><div><h3>{item.question}</h3><p>{questionBySlug(item.slug)?.summary}</p></div><ArrowRight/></Link>)}</div></section><section className="final-cta"><div className="container-wide"><div><p className="eyebrow light">Need this applied to your property?</p><h2>Ask J&L Welch to inspect and quote.</h2><p>Detailed written quotations for suitable roofing work across the North East.</p></div><Button asChild size="lg" className="answer-accent"><Link href="/request-a-quote">Request a quotation <ArrowRight/></Link></Button></div></section></main>}
